# Generated by Django 2.1.5 on 2019-03-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(default='image Title', max_length=100)),
                ('img_description', models.CharField(default='This is an image description', max_length=200)),
                ('img_uri', models.CharField(default='Image Uri', max_length=200)),
                ('img_usertag', models.CharField(default='Image Tag', max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
