# Generated by Django 2.1.5 on 2019-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearcheng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='image',
            field=models.ImageField(default='default', upload_to='mdeia'),
            preserve_default=False,
        ),
    ]
