# Generated by Django 2.1.5 on 2019-04-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearcheng', '0002_imagestore_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='img_category',
            field=models.CharField(default='picture', max_length=150),
        ),
    ]
