# Generated by Django 2.1.5 on 2019-04-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearcheng', '0003_imagestore_img_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('thumbnail', 'thumbnail')], default='', max_length=256),
        ),
    ]
