# Generated by Django 2.1.5 on 2019-04-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearcheng', '0004_imagestore_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestore',
            name='file_type',
        ),
    ]
