# Generated by Django 2.1.5 on 2019-04-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgsearcheng', '0005_remove_imagestore_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='img_xml',
            field=models.FileField(blank=True, null=True, upload_to='xmlfiles'),
        ),
    ]
